/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AppRouteImport } from './routes/app'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as TabsMeRouteImport } from './routes/_tabs.me'
import { Route as TabsMarketplaceRouteImport } from './routes/_tabs.marketplace'
import { Route as TabsHomeRouteImport } from './routes/_tabs.home'
import { Route as TabsChatsRouteImport } from './routes/_tabs.chats'
import { Route as ChatChatIdFeatureFeatureKeyRouteImport } from './routes/chat.$chatId.feature.$featureKey'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsMeRoute = TabsMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMarketplaceRoute = TabsMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHomeRoute = TabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChatsRoute = TabsChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => TabsRoute,
} as any)
const ChatChatIdFeatureFeatureKeyRoute =
  ChatChatIdFeatureFeatureKeyRouteImport.update({
    id: '/feature/$featureKey',
    path: '/feature/$featureKey',
    getParentRoute: () => ChatChatIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/profile': typeof ProfileRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/chats': typeof TabsChatsRoute
  '/home': typeof TabsHomeRoute
  '/marketplace': typeof TabsMarketplaceRoute
  '/me': typeof TabsMeRoute
  '/chat/$chatId': typeof ChatChatIdRouteWithChildren
  '/chat/$chatId/feature/$featureKey': typeof ChatChatIdFeatureFeatureKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/profile': typeof ProfileRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/chats': typeof TabsChatsRoute
  '/home': typeof TabsHomeRoute
  '/marketplace': typeof TabsMarketplaceRoute
  '/me': typeof TabsMeRoute
  '/chat/$chatId': typeof ChatChatIdRouteWithChildren
  '/chat/$chatId/feature/$featureKey': typeof ChatChatIdFeatureFeatureKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/app': typeof AppRoute
  '/profile': typeof ProfileRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/_tabs/chats': typeof TabsChatsRoute
  '/_tabs/home': typeof TabsHomeRoute
  '/_tabs/marketplace': typeof TabsMarketplaceRoute
  '/_tabs/me': typeof TabsMeRoute
  '/chat/$chatId': typeof ChatChatIdRouteWithChildren
  '/chat/$chatId/feature/$featureKey': typeof ChatChatIdFeatureFeatureKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/profile'
    | '/subscriptions'
    | '/chats'
    | '/home'
    | '/marketplace'
    | '/me'
    | '/chat/$chatId'
    | '/chat/$chatId/feature/$featureKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/profile'
    | '/subscriptions'
    | '/chats'
    | '/home'
    | '/marketplace'
    | '/me'
    | '/chat/$chatId'
    | '/chat/$chatId/feature/$featureKey'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/app'
    | '/profile'
    | '/subscriptions'
    | '/_tabs/chats'
    | '/_tabs/home'
    | '/_tabs/marketplace'
    | '/_tabs/me'
    | '/chat/$chatId'
    | '/chat/$chatId/feature/$featureKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  AppRoute: typeof AppRoute
  ProfileRoute: typeof ProfileRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  ChatChatIdRoute: typeof ChatChatIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/me': {
      id: '/_tabs/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof TabsMeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/marketplace': {
      id: '/_tabs/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof TabsMarketplaceRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/home': {
      id: '/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof TabsHomeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/chats': {
      id: '/_tabs/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof TabsChatsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/chat/$chatId/feature/$featureKey': {
      id: '/chat/$chatId/feature/$featureKey'
      path: '/feature/$featureKey'
      fullPath: '/chat/$chatId/feature/$featureKey'
      preLoaderRoute: typeof ChatChatIdFeatureFeatureKeyRouteImport
      parentRoute: typeof ChatChatIdRoute
    }
  }
}

interface TabsRouteChildren {
  TabsChatsRoute: typeof TabsChatsRoute
  TabsHomeRoute: typeof TabsHomeRoute
  TabsMarketplaceRoute: typeof TabsMarketplaceRoute
  TabsMeRoute: typeof TabsMeRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsChatsRoute: TabsChatsRoute,
  TabsHomeRoute: TabsHomeRoute,
  TabsMarketplaceRoute: TabsMarketplaceRoute,
  TabsMeRoute: TabsMeRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

interface ChatChatIdRouteChildren {
  ChatChatIdFeatureFeatureKeyRoute: typeof ChatChatIdFeatureFeatureKeyRoute
}

const ChatChatIdRouteChildren: ChatChatIdRouteChildren = {
  ChatChatIdFeatureFeatureKeyRoute: ChatChatIdFeatureFeatureKeyRoute,
}

const ChatChatIdRouteWithChildren = ChatChatIdRoute._addFileChildren(
  ChatChatIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  AppRoute: AppRoute,
  ProfileRoute: ProfileRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  ChatChatIdRoute: ChatChatIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
